### ISSUE TITLE
Transition animations broken in WebSharper 4 (Zafir)

### ISSUE THREAD

**Issue by cata** [intellifactory/websharper.ui.next#120]
See this snippet: http://try.websharper.com/snippet/0000DZ

The snippet works as expected in WS 3, but fails in WS4 - transitions are not animated.
I've also attached a [repro](https://github.com/intellifactory/websharper.ui.next/files/1051180/broken.transition.animation.zip) VS 2015 project

The transition animation(s) stop working as soon as the attribute list contains more than one attribute. 
For example (see snippet/repro), the following attribute combinations result in the bug:
 - `Attr.Class` + `Attr.AnimatedStyle`
 - `Attr.AnimatedStyle` + `Attr.AnimatedStyle`

Tested on Zafir.4.0.161.45-beta6 + Zafir.FSharp.4.0.161.45-beta6 + Zafir.UI.Next.4.0.134.36-beta6

Update - more info: 

attr.styleAnim is broken as well. In the repro code, try `attr.styleAnim (View.Const 1.0) (fun x -> sprintf "opacity:%f;" x) fade` + `Attr.Class "dummy"`

**Comment by cata** [comment]
Hi guys,

I was just wondering if you were able to repro this or whether you need more information.
I would be great if you could give some indication as to when/whether you plan to address this. Would help with planning :-)

**Comment by Tarmil** [comment]
Yes, I can reproduce this issue both on try.websharper and in a local project. I'm investigating it now, hoping that it's a quick fix but I'll notify you if it's a larger item.

**Comment by cata** [comment]
@Tarmil - This is great news Loïc, thank you for fixing this!
I will give the new release a try as soon as it's out and close the issue at that time.

**Comment by cata** [comment]
Fixed in 184f25bdad1b6e0635a2fc9e55ee3a35fd7a8fec - tested with  Zafir.UI.Next 4.0.150.54-beta7
