### ISSUE TITLE
Need a way to convert View<seq<'t>> to Seq<view<'t>> and vice-versa

### ISSUE THREAD

**Issue by endeavour** [intellifactory/websharper.ui.next#16]
This would be useful if for example you have a collection of shopping items in a ListModel and you want to calculate the total price.

**Comment by qwe2** [comment]
I use this snippet throughout my UI.Next projects for converting `seq<View<'T>> -> View<seq<'T>>` but I agree that this is probably common enough to go into the lib itself:

```fsharp
type View with
    static member Sequence views =
        views
        |> Seq.fold (View.Map2 (fun a b -> 
            seq { yield! a; yield b })) (View.Const Seq.empty)
```

I'm not sure about the other way around, though. I have yet to encounter a scenario where I'd need that.

**Comment by endeavour** [comment]
Thank you, this is very useful!
