### ISSUE TITLE
Templating: .Doc(...) should manage META/STYLES/SCRIPTS placeholders instead of exposing them to the user

### ISSUE THREAD

**Issue by granicz** [intellifactory/websharper.ui.next#23]
UI.Next templates work differently from sitelet templates at the moment, namely that the standard placeholders META/STYLES/SCRIPTS are treated as ordinary placeholders instead of being managed by the templating engine/TP.

**Comment by Tarmil** [comment]
Fixed in 113cc85413973f42a6b1bb3e45716d7b0f4f1d35
