### ISSUE TITLE
`client` in Warp app fails runtime

### ISSUE THREAD

**Issue by granicz** [intellifactory/websharper.ui.next#26]
This fails on the latest UI.Next and Warp (not yet released, compiled from source):

    open WebSharper
    open WebSharper.UI.Next
    open WebSharper.UI.Next.Html

    [<JavaScript>]
    module Client =
        open WebSharper.JavaScript

        let SayHi (e: Dom.Event) =
            JS.Alert "Hi!"

        let SayHello () =
            buttonAttr [Client.Attr.Handler "click" SayHi] [text "click me"]

    ...
    Warp.CreateApplication (fun ctx endpoints ->
        match endpoints with
        | Endpoints.Home ->
            Warp.Doc(
                Body = [
                    div [p [text "testing"]]
                    client <@ Client.SayHello() @>
                ]
            )

**Comment by Tarmil** [comment]
Fixed by websharper:9219d33cbb307505fa120b72cf1cf442a1ec171a
