### ISSUE TITLE
VS 2015 WebSharper Missing Item Templates

### ISSUE THREAD

**Issue by HMMiller** [intellifactory/websharper.ui.next#27]
On Visual Studio 2015 Enterprise / Windows Server 2012r2 Hyper-V SharePoint developer machine with 3.4.8.186 vsix and WebSharper.UI.Next project not seeing item templates from within any of the WebSharper project types. Ran devenv / with no difference - still Add New Item -> "No items found". Please advise.

Thanks,

Henri
NOTE: Login to websharper forum page broken (IE, Chrome) using github provider, which is reason for using this location. Sorry.

**Comment by qwe2** [comment]
I think this is a duplicate of https://github.com/intellifactory/websharper/issues/293.

If so it's a known limitation with VS templates (follow the discuccion for details). Script in the websharper GH repo: https://github.com/intellifactory/websharper.templates/blob/master/templates/sitelets-website/Setup.fsx

**Comment by Tarmil** [comment]
We should add the Setup.fsx file to all the web project templates though.

**Comment by HMMiller** [comment]
Thanks gents,

Got the project I was working on to work properly with your assistance. The F# MVC install seems to enable tooling correctly when adding new projects.

Thanks for reminding me - knew I was forgetting something from the 2013 install experience!

HMM

**Comment by fjoppe** [comment]
Hi,

The above script helped me many times before. But it seems that this problem also occurs in Visual Studio 2017 and 2019. The script does not solve this.

**Comment by granicz** [comment]
I just tested this in VS2019 with an offline sitelet project and I was able to add various items. Based on @Tarmil 's closing note in https://github.com/dotnet-websharper/core/issues/192, I'd think this was fixed for good - anyone else seeing this issue lately?
