### ISSUE TITLE
Many issues with Doc.FloatInput and Doc.IntInput

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper.ui.next#34]
The most obvious problem is with `Doc.FloatInput`. You can't enter a float value, e.g. "1.5", because as soon as you type "1.", the text is immediately replaced by "1". This is because "1." is successfully parsed and the var is updated, but then because the var was updated, the value is immediately formatted (using `string x`) and this simplifies the text to "1".

In fact, there are several usability problems with `Doc.FloatInput` and `Doc.IntInput`. Here are the requirements for numeric input as I see them:

- Whatever you type, the code should never change that text. If I enter " 007.00", that's what I should see. It should never be simplified. This is true for both `float` and `int` input.

- Empty input should be supported. If a dialog requires the user to enter a value, and there is no natural default value, the input field should initially be empty. The field can become empty again if the user deletes the text. And if the user just enters some spaces, this is empty too (and should not be simplified).

- A dialog with an **OK** or **Apply** button needs to know if the input field is currently invalid. The code as it stands today sets the var to be the last valid value, but the input field may have been changed since then and may now be invalid.

- Values need to be parsed correctly. Currently `Doc.FloatInput` uses `parseFloat`, and `Doc.IntInput` uses `parseInt`, but these are not the right functions to used (see [here](http://stackoverflow.com/a/13676265/2987720) and [here](http://stackoverflow.com/a/17106702/2987720)).

Here is my code for addressing these requirements.

First a helper function:

```fsharp
[<JavaScript>]
module String =
    /// The string is zero or more spaces.
    let blank (text: string) = text |> Seq.forall ((=) ' ')
```

Now the parsing:

```fsharp
[<Inline "Number($x)">]
let number x = X<float>

let (|ValidFloat|InvalidFloat|BlankFloat|) (text: string) =
    if String.blank text then BlankFloat
    else
        let x = number text
        if JS.IsNaN x then InvalidFloat else ValidFloat x

let (|ValidInt|InvalidInt|BlankInt|) text =
    match text with
    | _ when text |> Seq.exists ((=) '.') -> InvalidInt
    | ValidFloat x -> ValidInt (int x)
    | InvalidFloat -> InvalidInt
    | BlankFloat -> BlankInt
```

The var that we want to bind to the input field is of type `FormattedText<float>` or `FormattedText<int>`.

```fsharp
type FormattedText<'t> =
    | ValidText of text: string * value: 't
    | InvalidText of text: string
    | BlankText of spaces: string
```

Here is the code to connect the input field to the var:

```fsharp
let text = function
    | ValidText (text, _) -> text
    | InvalidText text -> text
    | BlankText text -> text

let formattedInput attrs tryParse (var: IRef<_>) =
    inputAttr [
        Attr.Concat attrs
        attr.typ "text"
        Attr.CustomValue var text (tryParse >> Some)
        Attr.DynamicClass "invalid-format" var.View (function InvalidText _ -> true | _ -> false)
    ] []
```

I like to show invalid input by changing the background color of the input field, which is what the `Attr.DynamicClass` is doing. This is optional of course, and this attribute could be added by the caller instead, as part of the `attrs` argument.

Finally here are my alternatives for `Doc.FloatInput` and `Doc.IntInput`. The `filter` function allows you to constrain the value, e.g. to require a positive number.

```fsharp
let floatInput attrs filter (var: IRef<_>) =
    let tryParse text =
        match text with
        | ValidFloat x when filter x -> ValidText (text, x)
        | BlankFloat -> BlankText text
        | _ -> InvalidText text
    formattedInput attrs tryParse var

let intInput attrs filter (var: IRef<_>) =
    let tryParse text =
        match text with
        | ValidInt x when filter x -> ValidText (text, x)
        | BlankInt -> BlankText text
        | _ -> InvalidText text
    formattedInput attrs tryParse var
```

Note that since `tryParse` is supplied to `formattedInput`, we can support other situations, such as parsing math expressions, e.g. "1.4 + 2/3". And since `FormattedText<'t>` is generic, other types could be supported, e.g. dates.

Here is an example usage. My application is CAD for mechanical design, and here I want the user to enter a setback distance for a chamfer, which will be applied to some edges:

```fsharp
let event f = fun _ _ -> f ()

let chamfer =
    let setback = Var.Create (BlankText "")

    let submit = Submitter.Create (View.Map Some setback.View) None
    submit.View
    |> View.Sink (function
        | Some (ValidText (_, setback)) -> JS.Alert (string setback)
        | _ -> ())

    let input = floatInput [attr.placeholder "distance"] (fun x -> x >= 0.) setback
    Template.ChamferDialog.Doc (
        Setback = [input],
        OnApply = event submit.Trigger)
```

**Comment by Tarmil** [comment]
> * Whatever you type, the code should never change that text. If I enter " 007.00", that's what I should see. It should never be simplified. This is true for both float and int input.

This is basically a bug in `Attr.CustomValue`, which compares strings when it should compare parsed values. I have a fix coming.

> * Empty input should be supported. If a dialog requires the user to enter a value, and there is no natural default value, the input field should initially be empty. The field can become empty again if the user deletes the text. And if the user just enters some spaces, this is empty too (and should not be simplified).

With the above fix, the user can delete the contents of the field and put whitespace, and it will be interpreted as 0.

> * A dialog with an OK or Apply button needs to know if the input field is currently invalid. The code as it stands today sets the var to be the last valid value, but the input field may have been changed since then and may now be invalid.

I think we can indeed have variants called something like `IntInputChecked` that would provide this functionality. I am not sure however if it a good idea to separate Blank from Invalid. I think it is up to the user to decide how they want to process blank input, as far as the library is concerned I think it should just be Invalid.

> * Values need to be parsed correctly. Currently Doc.FloatInput uses parseFloat, and Doc.IntInput uses parseInt, but these are not the right functions to used (see here and here).

I have a fix coming for this too. By the way there is a subtle bug in your implementation: checking for a period is not sufficient to distinguish float from int, since `"1e-1"` is a valid float but an invalid int :) I believe the right way to do this check is `x === x >> 0`.

Thanks for the reports!

**Comment by Bananas-Are-Yellow** [comment]
At first I tried to fix the immediate bug, and it sounds like that's what you intend to do too. But let me try to persuade you otherwise.

I think the fundamental problem here is trying to bind a textual input field to a `float`. Since the text can be *valid*, *invalid*, or *blank*, the var has to support these three cases.

They have different meaning. Blank means that the user has not entered a value yet. It doesn't mean 0. That's like saying that a `null` string means "", but in fact `null` represents no string at all.

The invalid case is important because if you see invalid text and then press OK (in my example), you  won't know what value will be used, unless you happen to remember what it was last time it was valid a few moments ago while you were editing the text. That's not a good user experience. If the text is invalid, the OK button would typically be disabled to show that the input data is incomplete. So the application code needs to know that it's invalid.

The application code can also decide whether the blank case is allowed. The value might be required, or it might be optional. But blank is not the same as invalid.

What this means is that in practice, the application code needs to use two vars:

- A `Var<FormattedText<float>>` to bind to the input field to represent the state of the dialog itself. The reality that the input text can be in any of three cases needs to be above board.

- A `Var<float>` (or `Var<float option>` if blank is allowed) which will be used by the downstream code that consumes the data from the dialog.

In my example, the OK button (if enabled) would push the value from the first var to the second one.

**Comment by Tarmil** [comment]
I do believe that both options should be available, hence my `IntInputChecked` proposal which would correspond to your implementation. Although I agree that we should encourage people to use the checked version, for example by calling it `IntInput` and the other one `IntInputUnchecked`.

About whether blank input should be a separate case: I am not entirely sure one way or the other, but I am starting to lean towards having it as a separate case.

**Comment by Tarmil** [comment]
One thing I noticed while doing tests: the `value` field of an `<input type="number">` in Chrome and Firefox is always either blank or valid. If I type invalid text then the value is reported as `""`. On the other hand, IE 10 does preserve the invalid value.

**Comment by Bananas-Are-Yellow** [comment]
I used `attr.typ "text"` so as to get full control.

**Comment by Bananas-Are-Yellow** [comment]
Thanks for pointing out the bug in my integer parsing. I've changed my code to this:

```fsharp
let intFormat = RegExp @"^\s*[+|-]?[0-9]+\s*$"

let (|ValidInt|InvalidInt|BlankInt|) text =
    match text with
    | ValidFloat x when intFormat.Test text -> ValidInt (int x)
    | BlankFloat -> BlankInt
    | _ -> InvalidInt
```

**Comment by Tarmil** [comment]
Using `type="text"` causes several usability problems though. On mobile, it doesn't prompt the browser to show a numeric keyboard. It also doesn't take locale into consideration: different languages have different number formats, and `type="number"` can determine this from the user's locale.

The standards-compliant way to go would be to use `type="number"`, and [`validity`](http://www.w3.org/TR/html/forms.html#dom-cva-validity) to distinguish blank from invalid input. Unfortunately this isn't supported by IE9-; I am looking into shims for this.

**Comment by Bananas-Are-Yellow** [comment]
I think I also wanted to use type "text" for another reason, which is that I don't want the up-down flippers to be present. Is there a way to stop those appearing? If you have no reason to snap values, they are just annoying.

**Comment by granicz** [comment]
So to summarize this discussion so far, given that the right shim can be found for IE9, we would rename/add a `Doc.IntInputUnchecked`/`Doc.IntInput` and their float variants, and these would use `type="number"`.  Is there any better alternative or a further enhancement you can suggest?

**Comment by Bananas-Are-Yellow** [comment]
I think that summary is right so far.

There was [another discussion](http://www.websharper.com/question/80181/websharper-uncaught-asynchronous-exception-error-keynotfoundexception) about `Doc.Select`, which I haven't studied very carefully, but I think that might be related. I think that was allowing for the selection to be unmade initially, which is rather like my 'blank' case for a number field.

**Comment by Bananas-Are-Yellow** [comment]
Excellent! Thanks.
