### ISSUE TITLE
Issue adding Websharper.UI.Next to client-server template project

### ISSUE THREAD

**Issue by malbertife** [intellifactory/websharper.ui.next#5]
Hi,
I installed the latest WebSharper VS Extension (3.0.46.130-rc1) on VS2013, created a new Client-Server template project and added the latest WebSharper.UI.Next (3.0.100.30-alpha) from Nuget 
The first build (with no modifications to the project) was successful, but now if I just rebuild the solution I get the error: 

`Error	2	The type provider constructor has thrown an exception: Could not load file or assembly 'WebSharper.Main, Version=3.0.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71' or one of its dependencies. Impossibile trovare il file specificato.	parse error FS3053	`

So I tried cloning the WebSharper.UI.Next repository from GitHub and building it with

`.\build.cmd`

`fsi.exe --exec .\build.fsx`

but I got this:

`[Error] C:\Users\Marco\AppData\Local\Temp\tmp3E63.tmp(1,1): System.IO.FileNotFoundException: Impossibile caricare il file o l'assembly 'WebSharper.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=451ee5fa653b377d' o una delle relative dipendenze. Impossibile trovare il file specificato.
System.Exception: Non-zero exit code: 1
  in <StartupCode$IntelliFactory-Build>.$WebSharper.Execute@124.Invoke(String message)
   in IntelliFactory.Build.WebSharperUtility.Execute(AppDomain dom, String exe, IEnumerable``1 args)
   in IntelliFactory.Build.WebSharperProject.build()
   in <StartupCode$IntelliFactory-Build>.$Solutions.Build@38.Invoke(AppDomain dom)
   in IntelliFactory.Build.Solution.WithDomain[T](FSharpFunc``2 f)
   in IntelliFactory.Build.BuildTool.Dispatch(Solution sln)
   in <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Users\Marco\repo_github\websharper.ui.next\build.fsx:riga 23
Stopped due to error`

The previous versions of WebSharper and UI.Next work fine.

**Comment by louthy** [comment]
I also have this problem.

**Comment by Tarmil** [comment]
The issue is due to the templating type provider. If you don't use it, then you can manually remove the reference to `WebSharper.UI.Next.Templating` as a temporary workaround until we find a fix.
