### ISSUE TITLE
warning MSB3061: Unable to delete file ...

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper.ui.next#52]
I reported this in the [WebSharper Forum](http://www.websharper.com/question/80306/warning-msb3061-unable-to-delete-file). I can now reproduce it quite simply with a new Visual Studio solution and only two projects.

I'm using Visual Studio 2015, if that makes any difference, and .NET 4.6 with F# 4.0.

It seems I can't upload a ZIP file of the solution (file type not supported), so here's how to recreate it:

1. Create a new solution.
1. Create WebSharper Library project called `Library`.
1. Create a Visual F# Library project called `Core`.
1. Add a project reference from `Library` to `Core`.
1. I am using .NET 4.6 with F# 4.0, and that's how `Core` was set up. So I had to change the project properties for the `Library` project to be the same (the WebSharper template created the project using F# 3.0).
1. Add packages `WebSharper` and `WebSharper.UI.Next` to the `Library` project.
1. Verify that you can build the solution.

To set up the conditions for the problem, do this:

1. Clean the solution.
1. Build the `Core` project only.
1. Open the `Main.fs` source file from the `Library` project.

At this point, a security dialog will appear saying: _You have opened a source code file in a project that references a type provider_. It shows that the type provider assembly is `WebSharper.UI.Next.Templating.dll`. Press the **Enable** button.

To produce the problem:

1. Close Visual Studio.
1. Reopen the solution and wait 20 seconds.
1. Clean the solution.

You will find that `Core.dll` is locked:

    warning MSB3061: Unable to delete file "<path>\Core\bin\Debug\Core.dll". Access to the path '<path>\bin\Debug\Core.dll' is denied.

The problem only occurs if `Main.fs` is open, so if you close `Main.fs` and restart Visual Studio, you will now be able to clean the solution successfully.

Also, if you expand the project references for the `Library` project and remove the reference to `WebSharper.UI.Next.Templating`, the problem will not occur.

**Comment by Tarmil** [comment]
Thanks for the detailed report! I can reproduce your steps. It looks like there is a problem with the way we load references in the templating type provider. I will look into it.
