### ISSUE TITLE
TemplateProvider example

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellifactory/websharper.ui.next#59]
I found `TemplateProvider` TP in the sources. Is there an example of its usage?

**Comment by Kimserey** [comment]
The doc has a section on it [https://github.com/intellifactory/websharper.ui.next/blob/master/docs/Templates.md](https://github.com/intellifactory/websharper.ui.next/blob/master/docs/Templates.md). Hope this help.

**Comment by vasily-kirichenko** [comment]
Excellent! Thanks.
