### ISSUE TITLE
Q:  Time based events on Var change and/or onblur equivalents

### ISSUE THREAD

**Issue by louthy** [intellifactory/websharper.ui.next#6]
Sorry if this the wrong place to ask.  I am just getting up to speed with Websharper and UI.Next.

I have a form that I want to auto-save when the user leaves a textbox (onblur) and/or after a certain amount of time not-typing (whilst focussed in a textbox).  I don't see anything obvious in the API docs for `Var` or `Doc.Input` that can aid me.  Any advice?

**Comment by SimonJF** [comment]
Hi,

Sounds like you'll be wanting Attr.Handler:

```
static member Handler : name: string -> callback: (DomEvent -> unit) -> Attr
```

You'll need to make the handler attribute with your onblur autosave callback, and specify this when creating your input box.

You can find an example here:

https://github.com/intellifactory/samples.todomvc/blob/master/src/Client.fs#L135

Hope that helps; feel free to get back to me with any questions!

Simon.

**Comment by louthy** [comment]
Hi @SimonJF thanks for the quick response that works perfectly.  Just one final Q, I can't for the life of me find where `Dom.Event`/`DomEvent` is declared.  It doesn't appear to be AutoOpened and I have these namespaces/assemblies setup as with the sample:

```F#
open WebSharper
open WebSharper.UI.Next
open WebSharper.UI.Next.Html
open WebSharper.UI.Next.Notation
```

Obviously I can get by with type inference, but it seems odd the I can't 'go to definition' in VS or find it in the UI.Next source.

**Comment by qwe2** [comment]
Dom.Event actually comes from WebSharper and not UI.Next. It's [in the stdlib](https://github.com/intellifactory/websharper/blob/725a439cd3512ed2cad83c603275daddcac9f4d5/src/stdlib/WebSharper.JavaScript/Dom.fs#L465) being opened with `WebSharper.JavaScript`.

**Comment by louthy** [comment]
Great, thanks!
