### ISSUE TITLE
View.Sequence broken?

### ISSUE THREAD

**Issue by ca-ta** [intellifactory/websharper.ui.next#67]
I've just updated to latest WebSharper.UI.Next (3.6.6.202).
Prior to the update, I've used the following to implement ``View.Sequence` functionality (see #16):

```
    type View with
        static member Sequence views =
            views
            |> Seq.fold (View.Map2 (fun a b -> 
                seq { yield! a; yield b })) (View.Const Seq.empty)
```
This (while perhaps not optimal in terms of performance) works great.
Switching to the View.Sequence implementation provided in 3.6.6.202 breaks our client app - the app fails to render the expected content (tested in Chrome, Firefox and IE 11 ). No exceptions are thrown.
The particular scenario I am using View.Sequence in is something like this:

```
    let f x = 
        x
        |> View.MapSeqCached (fun x -> x.View)
        |> View.Map View.Sequence
        |> View.Join

```
I've confirmed that the implementation in #16 continues to work with  3.6.6.202  - that is what we are currently using as a stop-gap.

**Comment by qwe2** [comment]
Could you please provide a bit more context on how you are using the `f` function? I have tried it on some trivial cases but I can't seem to reproduce the error.

**Comment by ca-ta** [comment]
@qwe2 - thank you for looking into it.
I will try to isolate the relevant code from our app and create a repro. I expect to have the repro by end of Friday.

**Comment by ca-ta** [comment]
@qwe2 - repro added in #68 

The current implementation of `View.Sequence` freezes *all* UI updates when the input sequence is empty. The implementation in #16 works correctly. 
Run the test project for instructions on how to reproduce the bug.

**Comment by qwe2** [comment]
Thanks a lot for taking the time to investigate this further! Indeed there is a problem with the implementation of `Snap.Sequence` where the continuations won't be called on an empty sequence.

**Comment by ca-ta** [comment]
Glad to be able to help - thank you for the fix! :+1:
