### ISSUE TITLE
Abnormal behavior of View.Sequence 

### ISSUE THREAD

**Issue by fpawel** [intellifactory/websharper.ui.next#70]
View.Sequence fails on empty sequences without the possibility to catch an exception in the try-block
For example this `Doc` never be rendered:
```
let xs : View<int> list = []
try
    View.Sequence xs
with _ ->
    View.Const Seq.empty
|> View.Map( fun _ -> Doc.TextNode "never be rendered" )
|> Doc.EmbededView
```

**Comment by qwe2** [comment]
Are you using the latest version of UI.Next. I remember fixing something like this: https://github.com/intellifactory/websharper.ui.next/issues/67

**Comment by fpawel** [comment]
Apparently, yes. `..\packages\WebSharper.UI.Next.3.6.8.204\lib\net40\WebSharper.UI.Next.dll ' and in packages.config `<package id="WebSharper.UI.Next" version="3.6.8.204" targetFramework="net45" />`

**Comment by qwe2** [comment]
I took a look and it seems we haven't done a release yet since the fix which is quite weird but the problem is actually fixed. We really should do a stack release in the following days. Until then you can use the alternative implementation from the other issue that doesn't break for empty lists.

**Comment by qwe2** [comment]
The latest package is released now.
