### ISSUE TITLE
SVG data-template does not display

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [intellifactory/websharper.ui.next#94]
I want to inject inline SVG into my page. So I created a data template like this:

```xml
<svg data-template="MyIcon" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
    ...
```

I can successfully inject this into my page using `Template.MyIcon.Doc ()` but the SVG does not get displayed. If I open the Developer Tools in Chrome and look at the Elements page, I can see what looks like correct SVG elements. If I then use the _Edit as HTML_ command and just insert a space, my SVG icon then gets displayed.

I think I understand why.

When the browser parses HTML text, the `xmlns` attribute tells it that this element and all nested elements are part of the SVG namespace. But if you create nodes using the DOM, you have to use `createElementNS` and specify the namespace for each node (not just the parent node) at the time you create it.

This is done when you create SVG nodes in F# since they all go through `Doc.SvgElement`, which creates nodes in the SVG namespace. But this is not done when an SVG data template is used. So all the SVG nodes are created with the default namespace, which is why they do not display. If you then use the _Edit as HTML_ command, Chrome reparses the HTML text and creates correct nodes instead.

What is the best workaround for this? I thought of copying the `Doc` tree returned from `Template.MyIcon.Doc ()` and calling `Doc.SvgElement` for each node. I can cast the `Doc` to an `Elt` since I know I have a single root element. But I can't find a way of traversing the structure.

Or is there a better workaround?

**Comment by Tarmil** [comment]
Thanks for the report. This looks like an accurate assessment of the cause of the problem.

I can't really think of a way to work around the issue with the current UI.Next, but it should be quick enough to fix the templating engine to create any `<svg>` node and all of its children with `Doc.SvgElement` instead of `Doc.Element`.

**Comment by Bananas-Are-Yellow** [comment]
Thanks for fixing it so quickly. In the meantime, here is my rather brutal workaround:

```fsharp
let fix (svg: Doc) =
    let inject parent =
        (svg :?> Elt).Html
        |> JQuery.ParseHTML 
        |> Array.fold (fun (parent: Dom.Node) child -> parent.AppendChild child) parent
        |> ignore
    spanAttr [on.afterRender inject] []

let create () =
    let kiwi = Template.KiwiIcon.Doc () 
    let chamfer = Template.ChamferIcon.Doc ()

    Doc.Concat [fix kiwi; fix chamfer]
```
